### ISSUE TITLE
file searches not working

### ISSUE THREAD

**Issue by Avishekk4121** [YaxinCheng/Tonnerre#1]
when searching through the files, either by name or by content only google one's shows up

**Comment by YaxinCheng** [comment]
Sorry that I've not actively maintained the project for a while. The is possibly caused by permission issues. Tonnerre starts a sub-program called TonnerreIndexHelper that indexes files on your system, so that they can be searched. Please make sure the index helper is running ( you can find it from Activity Monitor), and make sure Tonnerre has the permission to access files (from System Preferences, you probably need to give it full disk access permission as it was not a thing when Tonnerre was firstly developed).

Thanks for the feedback, and hope this helps

**Comment by Avishekk4121** [comment]
is there any other way to get the permission to access of all the folders? or automatically launch the TonnerreIndexHelper?

**Comment by YaxinCheng** [comment]
If I recall correctly, the permission window should pop up automatically when it tries to index your files. There is a way to manually launch TonnerreIndexHelper:
* Right click Tonnerre.app
* Choose `Show Package Contents`
* Under Contents - Applications, you should see `TonnerreIndexHelper.app`
* Double click it to launch

**Comment by Avishekk4121** [comment]
Hi @YaxinCheng, is there any way that we can merge the searches. Like i need to search for the apps as well as file at the same time. I don't want to write the file keyword everytime i search for files.

**Comment by YaxinCheng** [comment]
There is no GUI to do it. But I did consider it. The fallback provider is called `defaultProvider`, and it is can be set through `UserDefaults` with key `Tonnerre.Provider.Default`. You can put the provider id, in your case `Tonnerre.Provider.BuiltIn.FileNameSearchService`, then it will override the default google search when no result is available.

**Comment by Avishekk4121** [comment]
i do want the google search. However, i want to search for files without writing the keyword file before the file name.
suppose i am searching for xcode. So the result i want is like the xcode app on top and local files related to xcode after that.
i want to combine the app searches and file searches. Is there a way to do that? Like in spotlight there is section wise division between the related app names and file names.

**Comment by Avishekk4121** [comment]
basically i want to combine the results of  **Tonnerre.Provider.BuiltIn.FileNameSearchService**  & **Tonnerre.Provider.BuiltIn..LaunchService**
also can you help me understand about how the keyword "file" and "content" are modifying the behaviour of search.

**Comment by YaxinCheng** [comment]
The combined default provider is not possible from the current code, but you want to make a fork for it, that will not take too long I believe. 

> can you help me understand about how the keyword "file" and "content" are modifying the behaviour of search.

Basically, Tonnerre captures the first word as a keyword, then try to initialize service providers based on the keyword. So when you type `file`, it will find the service provider for file search. If I remember correctly, service providers can be activated by only the prefix, for example you can search files by using `f filename`. Hope this saves you a few key strokes
