### ISSUE TITLE
Mouse selection not working

### ISSUE THREAD

**Issue by Avishekk4121** [YaxinCheng/Tonnerre#2]
while searching for files or web search can we enable the mouse search as well.
i mean we are able to do it by pressing up and down button but not with mouse clicks when the results are open.
Can we acheive that ?

**Comment by Avishekk4121** [comment]
Also when there are more results, there is no way one can check it. The scroller is not there as well.

**Comment by YaxinCheng** [comment]
As explained in another repo, the missing mouse support was by design. The native NSTableView has the problem of memory leaking, and the LiteTableView I developed was meant to be simple and keyboard only.
